repos:
  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
        args: [--line-length=120]
        exclude: ^(\.venv_project/|\.venv_new/|venv/|node_modules/)
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]
        exclude: ^(\.venv_project/|\.venv_new/|venv/|node_modules/)
  - repo: https://github.com/pycqa/flake8
    rev: 7.2.0
    hooks:
      - id: flake8
        args: ["--max-line-length=120", "--extend-ignore=E203"]
        exclude: ^(\.venv_project/|\.venv_new/|venv/|node_modules/)
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.44.0
    hooks:
      - id: markdownlint
        stages: [manual, pre-commit, pre-push]
        args: [--fix, --config, .config/.markdownlint.json]
        files: ^(README|CHANGELOG|\.github\/issues).*\.md$
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
        exclude: ^(\.venv_project/|\.venv_new/|venv/|node_modules/|\.secrets\.baseline$)
      - id: check-yaml
        exclude: ^(\.venv_project/|\.venv_new/|venv/|node_modules/)
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args: ["--baseline", ".secrets.baseline"]
        exclude: ^(\.venv_project/|\.venv_new/|venv/|node_modules/)
  - repo: local
    hooks:
      - id: spectral-lint
        name: Spectral OpenAPI lint
        language: node
        entry: npx --no-install spectral lint openapi_3_1_demo.json --format stylish
        types: [json, yaml]
        files: ^openapi_3_1_demo\.json$
        pass_filenames: false
        stages: [manual, pre-commit, pre-push]
 
